[package]
name = "airpods-notify"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
futures = "0.3.25"
tokio-stream = "0.1"
btleplug = { version = "0.10", features = ["serde"] }
notify-rust = { version = "4.6.0", features = [ "images" ] }